apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: ghcr.io/davidpestana/aplicacion-node-proyecto-k8s:v2.0.0
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-secret
