apiVersion: v1
kind: Service
metadata:
  name: aplicacion
  namespace: proyecto
spec:
  selector:
    app: aplicacion   # debe coincidir con las labels del Deployment
  ports:
    - port: 80         # puerto que expone el servicio
      targetPort: 80   # puerto en el contenedor de Node.js
  type: ClusterIP
