apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-kube-prom
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 75.18.1
      # helm:
      #   valueFiles:
      #     - $values/base/monitoring/kube-prom.values.yaml
      #     - $values/environments/eks-prod-eu-central-1/overlay/monitoring/kube-prom.values.yaml

    - repoURL: https://github.com/llamaliticaAI/infrastructure.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true     

